language: python
python:
  - "3.6"

branches:
  only:
  - master

env:
  global:
    - PYTHON_HOME=pupil-lib

install:
  - "python setup.py install"

script:
  - "python -m pytest --capture=no pupillib/tests"
