language: python
python:
  - "3.6"

branches:
  only:
  - master

env:
  global:
    - PYTHON_HOME=pupil-lib/pupillib

install:
  - "python setup.py install"

script:
  - "cd pupillib"
  - "python -m pytest --capture=no tests"
